stages:
  - test
  - sync

test_patient_zero:
  stage: test
  image: node:22
  only:
    - main
  script:
    - cd PatientZero
    - npm ci
    - npm run test:run

sync_to_github:
  stage: sync
  needs:
    - test_patient_zero
  variables:
    GIT_DEPTH: 0
  only:
    - main
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"

    # Ajouter GitHub
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/PatientZero.git

    # Push vers GitHub
    - git push github HEAD:main --force
